services:
  deluge-next:
    container_name: htpc-deluge-next
    image: ghcr.io/jokejason/deluge-next:latest
    ports:
      - "3000:3000"
    environment:
      - DELUGE_URL=${DELUGE_URL}
      - DELUGE_PASSWORD=${DELUGE_PASSWORD}
      - DELUGE_TIMEOUT=${DELUGE_TIMEOUT}
